# Citation: https://github.com/marketplace/actions/deploy-to-heroku
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cd client && npm test
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "csc301store"
          heroku_email: "yatzu.wang@mail.utoronto.ca"